import type {
  StudentProfile,
  TopicMastery,
  DiagnosticAttempt,
  StudyPlan,
  StudyPlanItem,
  TutorSession,
} from '@/types';

export const DEMO_STUDENT_ID = '00000000-0000-4000-a000-000000000001';
export const DEMO_ADMIN_ID = '00000000-0000-4000-a000-000000000002';
export const DEMO_PARENT_ID = '00000000-0000-4000-a000-000000000003';

/**
 * Dedicated Pre-populated Demo Student Profile
 * Clearly flagged with isDemo: true, role: 'student'
 */
export const DEMO_STUDENT_PROFILE: StudentProfile = {
  id: DEMO_STUDENT_ID,
  email: 'demo.student@aiexamtutor.internal',
  fullName: 'Shamil',
  targetExam: 'ECAT',
  examYear: 2026,
  role: 'student',
  targetScore: 360,
  baselineScore: 240,
  currentScoreEstimate: 268,
  streakDays: 4,
  avatarUrl: 'https://picsum.photos/seed/demo-student/100/100',
  isDemo: true,
  lastActiveAt: new Date().toISOString(),
  createdAt: '2026-09-01T08:00:00.000Z',
  updatedAt: new Date().toISOString(),
};

/**
 * Dedicated Pre-populated Demo Parent Profile
 * Clearly flagged with isDemo: true, role: 'parent'
 */
export const DEMO_PARENT_PROFILE: StudentProfile = {
  id: DEMO_PARENT_ID,
  email: 'parent.guardian@aiexamtutor.internal',
  fullName: 'Mrs. Saima Khan (Parent / Guardian)',
  targetExam: 'ECAT',
  examYear: 2026,
  role: 'parent',
  targetScore: 360,
  baselineScore: 240,
  currentScoreEstimate: 268,
  streakDays: 4,
  avatarUrl: 'https://picsum.photos/seed/parent-guardian/100/100',
  isDemo: true,
  lastActiveAt: new Date().toISOString(),
  createdAt: '2026-09-01T08:00:00.000Z',
  updatedAt: new Date().toISOString(),
};

/**
 * Dedicated Pre-populated Demo Admin Profile
 * Clearly flagged with isDemo: true, role: 'admin'
 */
export const DEMO_ADMIN_PROFILE: StudentProfile = {
  id: DEMO_ADMIN_ID,
  email: 'admin.curriculum@aiexamtutor.internal',
  fullName: 'Engr. Shamil Shahbaz',
  targetExam: 'ECAT',
  examYear: 2026,
  role: 'admin',
  targetScore: 400,
  baselineScore: 380,
  currentScoreEstimate: 395,
  streakDays: 28,
  avatarUrl: 'https://picsum.photos/seed/curriculum-admin/100/100',
  isDemo: true,
  lastActiveAt: new Date().toISOString(),
  createdAt: '2026-08-15T08:00:00.000Z',
  updatedAt: new Date().toISOString(),
};

/**
 * Pre-populated Topic Masteries for the Demo Student
 */
export const DEMO_TOPIC_MASTERIES: TopicMastery[] = [
  {
    id: 'mastery-demo-01',
    studentId: DEMO_STUDENT_ID,
    topicId: 'topic-phy-centripetal-force',
    subjectId: 'subj-physics',
    masteryScore: 38,
    masteryLevel: 'novice',
    totalAttempted: 12,
    correctCount: 4,
    streakCount: 0,
    lastTestedAt: '2026-09-08T14:30:00.000Z',
    needsReview: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mastery-demo-02',
    studentId: DEMO_STUDENT_ID,
    topicId: 'topic-phy-coulomb-law',
    subjectId: 'subj-physics',
    masteryScore: 82,
    masteryLevel: 'proficient',
    totalAttempted: 15,
    correctCount: 13,
    streakCount: 4,
    lastTestedAt: '2026-09-09T10:15:00.000Z',
    needsReview: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mastery-demo-03',
    studentId: DEMO_STUDENT_ID,
    topicId: 'topic-chem-le-chatelier',
    subjectId: 'subj-chemistry',
    masteryScore: 48,
    masteryLevel: 'developing',
    totalAttempted: 10,
    correctCount: 5,
    streakCount: 1,
    lastTestedAt: '2026-09-07T16:00:00.000Z',
    needsReview: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mastery-demo-04',
    studentId: DEMO_STUDENT_ID,
    topicId: 'topic-math-chain-rule',
    subjectId: 'subj-mathematics',
    masteryScore: 62,
    masteryLevel: 'developing',
    totalAttempted: 14,
    correctCount: 9,
    streakCount: 2,
    lastTestedAt: '2026-09-09T18:45:00.000Z',
    needsReview: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mastery-demo-05',
    studentId: DEMO_STUDENT_ID,
    topicId: 'topic-bio-cell-structure',
    subjectId: 'subj-biology',
    masteryScore: 78,
    masteryLevel: 'proficient',
    totalAttempted: 16,
    correctCount: 13,
    streakCount: 3,
    lastTestedAt: '2026-09-09T11:00:00.000Z',
    needsReview: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mastery-demo-05b',
    studentId: DEMO_STUDENT_ID,
    topicId: 'topic-bio-biological-molecules',
    subjectId: 'subj-biology',
    masteryScore: 65,
    masteryLevel: 'developing',
    totalAttempted: 12,
    correctCount: 8,
    streakCount: 2,
    lastTestedAt: '2026-09-08T15:30:00.000Z',
    needsReview: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mastery-demo-05c',
    studentId: DEMO_STUDENT_ID,
    topicId: 'topic-bio-enzymes-bioenergetics',
    subjectId: 'subj-biology',
    masteryScore: 42,
    masteryLevel: 'novice',
    totalAttempted: 10,
    correctCount: 4,
    streakCount: 0,
    lastTestedAt: '2026-09-07T14:20:00.000Z',
    needsReview: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mastery-demo-05d',
    studentId: DEMO_STUDENT_ID,
    topicId: 'topic-bio-mendelian-genetics',
    subjectId: 'subj-biology',
    masteryScore: 70,
    masteryLevel: 'proficient',
    totalAttempted: 14,
    correctCount: 10,
    streakCount: 3,
    lastTestedAt: '2026-09-09T13:45:00.000Z',
    needsReview: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mastery-demo-06',
    studentId: DEMO_STUDENT_ID,
    topicId: 'topic-logic-syllogisms',
    subjectId: 'subj-logical-reasoning',
    masteryScore: 85,
    masteryLevel: 'mastered',
    totalAttempted: 10,
    correctCount: 9,
    streakCount: 5,
    lastTestedAt: '2026-09-09T12:00:00.000Z',
    needsReview: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mastery-demo-06b',
    studentId: DEMO_STUDENT_ID,
    topicId: 'topic-logic-conditional-reasoning',
    subjectId: 'subj-logical-reasoning',
    masteryScore: 68,
    masteryLevel: 'developing',
    totalAttempted: 8,
    correctCount: 5,
    streakCount: 1,
    lastTestedAt: '2026-09-08T16:10:00.000Z',
    needsReview: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mastery-demo-06c',
    studentId: DEMO_STUDENT_ID,
    topicId: 'topic-logic-pattern-series',
    subjectId: 'subj-logical-reasoning',
    masteryScore: 80,
    masteryLevel: 'proficient',
    totalAttempted: 12,
    correctCount: 10,
    streakCount: 4,
    lastTestedAt: '2026-09-09T17:00:00.000Z',
    needsReview: false,
    updatedAt: new Date().toISOString(),
  },
];

/**
 * Pre-populated Diagnostic Result for Demo Student (ECAT)
 */
export const DEMO_DIAGNOSTIC_ATTEMPT: DiagnosticAttempt = {
  id: 'diag-attempt-demo-01',
  diagnosticId: 'diag-ecat-prelim',
  diagnosticTestId: 'diag-ecat-prelim',
  studentId: DEMO_STUDENT_ID,
  studentName: 'Shamil',
  examType: 'ECAT',
  status: 'completed',
  startedAt: '2026-09-05T09:00:00.000Z',
  completedAt: '2026-09-05T09:42:15.000Z',
  totalQuestions: 30,
  attemptedQuestions: 30,
  totalScore: 240,
  maxScore: 400,
  overallAccuracy: 62,
  percentage: 60,
  percentileEstimate: 78,
  subjectBreakdown: {
    'subj-mathematics': {
      subjectId: 'subj-mathematics',
      subjectName: 'Mathematics',
      score: 72,
      maxScore: 120,
      totalQuestions: 10,
      attemptedQuestions: 10,
      correctCount: 6,
      accuracy: 60,
      topics: [
        {
          topicId: 'topic-math-quadratic-equations',
          topicName: 'Quadratic Equations & Roots',
          subjectId: 'subj-mathematics',
          subjectName: 'Mathematics',
          chapterName: 'Algebra & Number Systems',
          attempted: 5,
          correct: 4,
          accuracy: 80,
          classification: 'strong',
          averageTimeSeconds: 58,
          confidenceDistribution: { low: 0, medium: 2, high: 3, unspecified: 0 },
          severity: 'none',
          yieldPriority: 5,
        },
        {
          topicId: 'topic-math-chain-rule',
          topicName: 'Chain Rule & Implicit Differentiation',
          subjectId: 'subj-mathematics',
          subjectName: 'Mathematics',
          chapterName: 'Differentiation & Calculus',
          attempted: 5,
          correct: 3,
          accuracy: 60,
          classification: 'developing',
          averageTimeSeconds: 84,
          confidenceDistribution: { low: 1, medium: 3, high: 1, unspecified: 0 },
          severity: 'minor',
          yieldPriority: 4,
        },
      ],
    },
    'subj-physics': {
      subjectId: 'subj-physics',
      subjectName: 'Physics',
      score: 76,
      maxScore: 120,
      totalQuestions: 10,
      attemptedQuestions: 10,
      correctCount: 6,
      accuracy: 63,
      topics: [
        {
          topicId: 'topic-phy-kinematics',
          topicName: 'Kinematics in One & Two Dimensions',
          subjectId: 'subj-physics',
          subjectName: 'Physics',
          chapterName: 'Mechanics & Dynamics',
          attempted: 4,
          correct: 3,
          accuracy: 75,
          classification: 'strong',
          averageTimeSeconds: 62,
          confidenceDistribution: { low: 0, medium: 1, high: 3, unspecified: 0 },
          severity: 'none',
          yieldPriority: 5,
        },
        {
          topicId: 'topic-phy-coulomb-law',
          topicName: "Coulomb's Law & Electric Fields",
          subjectId: 'subj-physics',
          subjectName: 'Physics',
          chapterName: 'Electrostatics',
          attempted: 3,
          correct: 2,
          accuracy: 67,
          classification: 'developing',
          averageTimeSeconds: 70,
          confidenceDistribution: { low: 1, medium: 1, high: 1, unspecified: 0 },
          severity: 'minor',
          yieldPriority: 4,
        },
        {
          topicId: 'topic-phy-centripetal-force',
          topicName: 'Centripetal Force & Banking of Roads',
          subjectId: 'subj-physics',
          subjectName: 'Physics',
          chapterName: 'Circular Motion & Rotational Dynamics',
          attempted: 3,
          correct: 1,
          accuracy: 33,
          classification: 'weak',
          averageTimeSeconds: 98,
          confidenceDistribution: { low: 2, medium: 1, high: 0, unspecified: 0 },
          severity: 'critical',
          yieldPriority: 5,
        },
      ],
    },
    'subj-chemistry': {
      subjectId: 'subj-chemistry',
      subjectName: 'Chemistry',
      score: 68,
      maxScore: 120,
      totalQuestions: 7,
      attemptedQuestions: 7,
      correctCount: 4,
      accuracy: 57,
      topics: [
        {
          topicId: 'topic-chem-atomic-structure',
          topicName: 'Atomic Structure & Quantum Numbers',
          subjectId: 'subj-chemistry',
          subjectName: 'Chemistry',
          chapterName: 'Fundamental Principles',
          attempted: 3,
          correct: 2,
          accuracy: 67,
          classification: 'developing',
          averageTimeSeconds: 65,
          confidenceDistribution: { low: 0, medium: 2, high: 1, unspecified: 0 },
          severity: 'minor',
          yieldPriority: 4,
        },
        {
          topicId: 'topic-chem-le-chatelier',
          topicName: "Le Chatelier's Principle & Equilibrium Shifts",
          subjectId: 'subj-chemistry',
          subjectName: 'Chemistry',
          chapterName: 'Chemical Equilibrium',
          attempted: 4,
          correct: 2,
          accuracy: 50,
          classification: 'weak',
          averageTimeSeconds: 88,
          confidenceDistribution: { low: 1, medium: 2, high: 1, unspecified: 0 },
          severity: 'moderate',
          yieldPriority: 4,
        },
      ],
    },
    'subj-english': {
      subjectId: 'subj-english',
      subjectName: 'English',
      score: 24,
      maxScore: 40,
      totalQuestions: 3,
      attemptedQuestions: 3,
      correctCount: 2,
      accuracy: 67,
      topics: [
        {
          topicId: 'topic-eng-subject-verb',
          topicName: 'Subject-Verb Agreement & Syntax Rules',
          subjectId: 'subj-english',
          subjectName: 'English',
          chapterName: 'Grammar & Mechanics',
          attempted: 3,
          correct: 2,
          accuracy: 67,
          classification: 'developing',
          averageTimeSeconds: 42,
          confidenceDistribution: { low: 0, medium: 2, high: 1, unspecified: 0 },
          severity: 'minor',
          yieldPriority: 3,
        },
      ],
    },
  },
  topicBreakdown: {
    'topic-phy-centripetal-force': {
      topicId: 'topic-phy-centripetal-force',
      topicName: 'Centripetal Force & Banking of Roads',
      subjectId: 'subj-physics',
      subjectName: 'Physics',
      chapterName: 'Circular Motion & Rotational Dynamics',
      attempted: 3,
      correct: 1,
      accuracy: 33,
      classification: 'weak',
      averageTimeSeconds: 98,
      confidenceDistribution: { low: 2, medium: 1, high: 0, unspecified: 0 },
      severity: 'critical',
      yieldPriority: 5,
    },
    'topic-chem-le-chatelier': {
      topicId: 'topic-chem-le-chatelier',
      topicName: "Le Chatelier's Principle & Equilibrium Shifts",
      subjectId: 'subj-chemistry',
      subjectName: 'Chemistry',
      chapterName: 'Chemical Equilibrium',
      attempted: 4,
      correct: 2,
      accuracy: 50,
      classification: 'weak',
      averageTimeSeconds: 88,
      confidenceDistribution: { low: 1, medium: 2, high: 1, unspecified: 0 },
      severity: 'moderate',
      yieldPriority: 4,
    },
    'topic-math-chain-rule': {
      topicId: 'topic-math-chain-rule',
      topicName: 'Chain Rule & Implicit Differentiation',
      subjectId: 'subj-mathematics',
      subjectName: 'Mathematics',
      chapterName: 'Differentiation & Calculus',
      attempted: 5,
      correct: 3,
      accuracy: 60,
      classification: 'developing',
      averageTimeSeconds: 84,
      confidenceDistribution: { low: 1, medium: 3, high: 1, unspecified: 0 },
      severity: 'minor',
      yieldPriority: 4,
    },
    'topic-phy-coulomb-law': {
      topicId: 'topic-phy-coulomb-law',
      topicName: "Coulomb's Law & Electric Fields",
      subjectId: 'subj-physics',
      subjectName: 'Physics',
      chapterName: 'Electrostatics',
      attempted: 3,
      correct: 2,
      accuracy: 67,
      classification: 'developing',
      averageTimeSeconds: 70,
      confidenceDistribution: { low: 1, medium: 1, high: 1, unspecified: 0 },
      severity: 'minor',
      yieldPriority: 4,
    },
    'topic-chem-atomic-structure': {
      topicId: 'topic-chem-atomic-structure',
      topicName: 'Atomic Structure & Quantum Numbers',
      subjectId: 'subj-chemistry',
      subjectName: 'Chemistry',
      chapterName: 'Fundamental Principles',
      attempted: 3,
      correct: 2,
      accuracy: 67,
      classification: 'developing',
      averageTimeSeconds: 65,
      confidenceDistribution: { low: 0, medium: 2, high: 1, unspecified: 0 },
      severity: 'minor',
      yieldPriority: 4,
    },
    'topic-eng-subject-verb': {
      topicId: 'topic-eng-subject-verb',
      topicName: 'Subject-Verb Agreement & Syntax Rules',
      subjectId: 'subj-english',
      subjectName: 'English',
      chapterName: 'Grammar & Mechanics',
      attempted: 3,
      correct: 2,
      accuracy: 67,
      classification: 'developing',
      averageTimeSeconds: 42,
      confidenceDistribution: { low: 0, medium: 2, high: 1, unspecified: 0 },
      severity: 'minor',
      yieldPriority: 3,
    },
    'topic-phy-kinematics': {
      topicId: 'topic-phy-kinematics',
      topicName: 'Kinematics in One & Two Dimensions',
      subjectId: 'subj-physics',
      subjectName: 'Physics',
      chapterName: 'Mechanics & Dynamics',
      attempted: 4,
      correct: 3,
      accuracy: 75,
      classification: 'strong',
      averageTimeSeconds: 62,
      confidenceDistribution: { low: 0, medium: 1, high: 3, unspecified: 0 },
      severity: 'none',
      yieldPriority: 5,
    },
    'topic-math-quadratic-equations': {
      topicId: 'topic-math-quadratic-equations',
      topicName: 'Quadratic Equations & Roots',
      subjectId: 'subj-mathematics',
      subjectName: 'Mathematics',
      chapterName: 'Algebra & Number Systems',
      attempted: 5,
      correct: 4,
      accuracy: 80,
      classification: 'strong',
      averageTimeSeconds: 58,
      confidenceDistribution: { low: 0, medium: 2, high: 3, unspecified: 0 },
      severity: 'none',
      yieldPriority: 5,
    },
  },
  difficultyBreakdown: {
    easy: { difficulty: 'easy', total: 10, attempted: 10, correct: 8, accuracy: 80 },
    medium: { difficulty: 'medium', total: 14, attempted: 14, correct: 8, accuracy: 57 },
    hard: { difficulty: 'hard', total: 6, attempted: 6, correct: 2, accuracy: 33 },
    exam_level: { difficulty: 'exam_level', total: 0, attempted: 0, correct: 0, accuracy: 0 },
  },
  timePerformance: {
    totalTimeSpentSeconds: 2535, // 42m 15s
    averageTimePerQuestionSeconds: 84,
    fastestQuestionSeconds: 38,
    slowestQuestionSeconds: 124,
    recommendedPacingSeconds: 90,
    pacingStanding: 'optimal',
  },
  confidenceBreakdown: {
    highConfidenceCount: 9,
    highConfidenceAccuracy: 78,
    mediumConfidenceCount: 15,
    mediumConfidenceAccuracy: 53,
    lowConfidenceCount: 6,
    lowConfidenceAccuracy: 33,
    unspecifiedCount: 0,
    calibrationStatus: 'well_calibrated',
    insightText:
      'Good metacognitive calibration. Your highest confidence answers achieved 78% accuracy. To boost your score, convert developing topics like Chain Rule and Atomic Structure into high confidence mastery.',
  },
  weakTopics: [
    {
      topicId: 'topic-phy-centripetal-force',
      topicName: 'Centripetal Force & Banking of Roads',
      subjectId: 'subj-physics',
      subjectName: 'Physics',
      chapterName: 'Circular Motion & Rotational Dynamics',
      attempted: 3,
      correct: 1,
      accuracy: 33,
      classification: 'weak',
      averageTimeSeconds: 98,
      confidenceDistribution: { low: 2, medium: 1, high: 0, unspecified: 0 },
      severity: 'critical',
      yieldPriority: 5,
    },
    {
      topicId: 'topic-chem-le-chatelier',
      topicName: "Le Chatelier's Principle & Equilibrium Shifts",
      subjectId: 'subj-chemistry',
      subjectName: 'Chemistry',
      chapterName: 'Chemical Equilibrium',
      attempted: 4,
      correct: 2,
      accuracy: 50,
      classification: 'weak',
      averageTimeSeconds: 88,
      confidenceDistribution: { low: 1, medium: 2, high: 1, unspecified: 0 },
      severity: 'moderate',
      yieldPriority: 4,
    },
  ],
  strongTopics: [
    {
      topicId: 'topic-math-quadratic-equations',
      topicName: 'Quadratic Equations & Roots',
      subjectId: 'subj-mathematics',
      subjectName: 'Mathematics',
      chapterName: 'Algebra & Number Systems',
      attempted: 5,
      correct: 4,
      accuracy: 80,
      classification: 'strong',
      averageTimeSeconds: 58,
      confidenceDistribution: { low: 0, medium: 2, high: 3, unspecified: 0 },
      severity: 'none',
      yieldPriority: 5,
    },
    {
      topicId: 'topic-phy-kinematics',
      topicName: 'Kinematics in One & Two Dimensions',
      subjectId: 'subj-physics',
      subjectName: 'Physics',
      chapterName: 'Mechanics & Dynamics',
      attempted: 4,
      correct: 3,
      accuracy: 75,
      classification: 'strong',
      averageTimeSeconds: 62,
      confidenceDistribution: { low: 0, medium: 1, high: 3, unspecified: 0 },
      severity: 'none',
      yieldPriority: 5,
    },
  ],
  developingTopics: [
    {
      topicId: 'topic-math-chain-rule',
      topicName: 'Chain Rule & Implicit Differentiation',
      subjectId: 'subj-mathematics',
      subjectName: 'Mathematics',
      chapterName: 'Differentiation & Calculus',
      attempted: 5,
      correct: 3,
      accuracy: 60,
      classification: 'developing',
      averageTimeSeconds: 84,
      confidenceDistribution: { low: 1, medium: 3, high: 1, unspecified: 0 },
      severity: 'minor',
      yieldPriority: 4,
    },
    {
      topicId: 'topic-phy-coulomb-law',
      topicName: "Coulomb's Law & Electric Fields",
      subjectId: 'subj-physics',
      subjectName: 'Physics',
      chapterName: 'Electrostatics',
      attempted: 3,
      correct: 2,
      accuracy: 67,
      classification: 'developing',
      averageTimeSeconds: 70,
      confidenceDistribution: { low: 1, medium: 1, high: 1, unspecified: 0 },
      severity: 'minor',
      yieldPriority: 4,
    },
    {
      topicId: 'topic-chem-atomic-structure',
      topicName: 'Atomic Structure & Quantum Numbers',
      subjectId: 'subj-chemistry',
      subjectName: 'Chemistry',
      chapterName: 'Fundamental Principles',
      attempted: 3,
      correct: 2,
      accuracy: 67,
      classification: 'developing',
      averageTimeSeconds: 65,
      confidenceDistribution: { low: 0, medium: 2, high: 1, unspecified: 0 },
      severity: 'minor',
      yieldPriority: 4,
    },
    {
      topicId: 'topic-eng-subject-verb',
      topicName: 'Subject-Verb Agreement & Syntax Rules',
      subjectId: 'subj-english',
      subjectName: 'English',
      chapterName: 'Grammar & Mechanics',
      attempted: 3,
      correct: 2,
      accuracy: 67,
      classification: 'developing',
      averageTimeSeconds: 42,
      confidenceDistribution: { low: 0, medium: 2, high: 1, unspecified: 0 },
      severity: 'minor',
      yieldPriority: 3,
    },
  ],
  unknownTopics: [],
  recommendedNextStep: {
    topicId: 'topic-phy-centripetal-force',
    topicName: 'Centripetal Force & Banking of Roads',
    subjectName: 'Physics',
    chapterName: 'Circular Motion & Rotational Dynamics',
    learningUnitUrl: '/student/learn/topic-phy-centripetal-force',
    reason:
      'Ranked #1 Critical Gap: 33% accuracy on diagnostic test. High-yield past paper topic (5-7% of Physics marks). Remediating this unit unlocks up to +16 ECAT marks.',
    priority: 1,
    currentAccuracy: 33,
    estimatedMinutesToMastery: 45,
  },
  answers: [],
  subjectScores: {
    'subj-mathematics': {
      score: 72,
      maxScore: 120,
      accuracyPercentage: 60,
    },
    'subj-physics': {
      score: 76,
      maxScore: 120,
      accuracyPercentage: 63,
    },
    'subj-chemistry': {
      score: 68,
      maxScore: 120,
      accuracyPercentage: 56,
    },
    'subj-english': {
      score: 24,
      maxScore: 40,
      accuracyPercentage: 60,
    },
  },
  detectedWeaknesses: [
    {
      topicId: 'topic-phy-centripetal-force',
      topicName: 'Centripetal Force & Banking of Roads',
      subjectName: 'Physics',
      severity: 'critical',
      accuracy: 33,
    },
    {
      topicId: 'topic-chem-le-chatelier',
      topicName: "Le Chatelier's Principle & Stress Response",
      subjectName: 'Chemistry',
      severity: 'moderate',
      accuracy: 45,
    },
    {
      topicId: 'topic-math-chain-rule',
      topicName: 'Chain Rule & Implicit Differentiation',
      subjectName: 'Mathematics',
      severity: 'minor',
      accuracy: 62,
    },
  ],
  aiDiagnosticSummary:
    'Demonstrated steady arithmetic and English basics, but critical velocity gaps exist in Rotational Dynamics (Centripetal Force) and Chemical Equilibrium shifts under pressure. Recommend prioritizing circular motion free-body diagrams and Le Chatelier temperature dependence before attempting speed drills.',
};

/**
 * Pre-populated Diagnostic Result for Demo Student (MDCAT)
 */
export const DEMO_MDCAT_DIAGNOSTIC_ATTEMPT: DiagnosticAttempt = {
  id: 'diag-attempt-demo-mdcat-01',
  diagnosticId: 'diag-mdcat-prelim',
  diagnosticTestId: 'diag-mdcat-prelim',
  studentId: DEMO_STUDENT_ID,
  studentName: 'Shamil',
  examType: 'MDCAT',
  status: 'completed',
  startedAt: '2026-09-06T09:00:00.000Z',
  completedAt: '2026-09-06T09:44:10.000Z',
  totalQuestions: 30,
  attemptedQuestions: 30,
  totalScore: 21,
  maxScore: 30,
  overallAccuracy: 70,
  percentage: 70,
  percentileEstimate: 82,
  subjectBreakdown: {
    'subj-biology': {
      subjectId: 'subj-biology',
      subjectName: 'Biology',
      score: 9,
      maxScore: 12,
      totalQuestions: 12,
      attemptedQuestions: 12,
      correctCount: 9,
      accuracy: 75,
      topics: [
        {
          topicId: 'topic-bio-cell-structure',
          topicName: 'Cell Structure & Organelle Functions',
          subjectId: 'subj-biology',
          subjectName: 'Biology',
          chapterName: 'Cell Biology',
          attempted: 12,
          correct: 9,
          accuracy: 75,
          classification: 'strong',
          averageTimeSeconds: 52,
          confidenceDistribution: { low: 1, medium: 3, high: 8, unspecified: 0 },
          severity: 'none',
          yieldPriority: 5,
        },
      ],
    },
    'subj-chemistry': {
      subjectId: 'subj-chemistry',
      subjectName: 'Chemistry',
      score: 5,
      maxScore: 9,
      totalQuestions: 9,
      attemptedQuestions: 9,
      correctCount: 5,
      accuracy: 56,
      topics: [
        {
          topicId: 'topic-chem-le-chatelier',
          topicName: "Le Chatelier's Principle & Equilibrium Shifts",
          subjectId: 'subj-chemistry',
          subjectName: 'Chemistry',
          chapterName: 'Chemical Equilibrium',
          attempted: 5,
          correct: 2,
          accuracy: 40,
          classification: 'weak',
          averageTimeSeconds: 85,
          confidenceDistribution: { low: 2, medium: 2, high: 1, unspecified: 0 },
          severity: 'critical',
          yieldPriority: 5,
        },
        {
          topicId: 'topic-chem-atomic-structure',
          topicName: 'Atomic Structure & Quantum Numbers',
          subjectId: 'subj-chemistry',
          subjectName: 'Chemistry',
          chapterName: 'Fundamental Principles',
          attempted: 4,
          correct: 3,
          accuracy: 75,
          classification: 'strong',
          averageTimeSeconds: 60,
          confidenceDistribution: { low: 0, medium: 1, high: 3, unspecified: 0 },
          severity: 'none',
          yieldPriority: 4,
        },
      ],
    },
    'subj-physics': {
      subjectId: 'subj-physics',
      subjectName: 'Physics',
      score: 4,
      maxScore: 6,
      totalQuestions: 6,
      attemptedQuestions: 6,
      correctCount: 4,
      accuracy: 67,
      topics: [
        {
          topicId: 'topic-phy-coulomb-law',
          topicName: "Coulomb's Law & Electric Fields",
          subjectId: 'subj-physics',
          subjectName: 'Physics',
          chapterName: 'Electrostatics',
          attempted: 6,
          correct: 4,
          accuracy: 67,
          classification: 'developing',
          averageTimeSeconds: 78,
          confidenceDistribution: { low: 1, medium: 3, high: 2, unspecified: 0 },
          severity: 'minor',
          yieldPriority: 4,
        },
      ],
    },
    'subj-english': {
      subjectId: 'subj-english',
      subjectName: 'English',
      score: 3,
      maxScore: 3,
      totalQuestions: 3,
      attemptedQuestions: 3,
      correctCount: 3,
      accuracy: 100,
      topics: [
        {
          topicId: 'topic-eng-subject-verb',
          topicName: 'Subject-Verb Agreement & Syntax Rules',
          subjectId: 'subj-english',
          subjectName: 'English',
          chapterName: 'Grammar & Mechanics',
          attempted: 3,
          correct: 3,
          accuracy: 100,
          classification: 'strong',
          averageTimeSeconds: 40,
          confidenceDistribution: { low: 0, medium: 0, high: 3, unspecified: 0 },
          severity: 'none',
          yieldPriority: 3,
        },
      ],
    },
    'subj-logical-reasoning': {
      subjectId: 'subj-logical-reasoning',
      subjectName: 'Logical Reasoning',
      score: 3,
      maxScore: 3,
      totalQuestions: 3,
      attemptedQuestions: 3,
      correctCount: 3,
      accuracy: 100,
      topics: [
        {
          topicId: 'topic-logic-syllogisms',
          topicName: 'Critical Deduction & Syllogisms',
          subjectId: 'subj-logical-reasoning',
          subjectName: 'Logical Reasoning',
          chapterName: 'Critical Thinking & Deduction',
          attempted: 3,
          correct: 3,
          accuracy: 100,
          classification: 'strong',
          averageTimeSeconds: 45,
          confidenceDistribution: { low: 0, medium: 0, high: 3, unspecified: 0 },
          severity: 'none',
          yieldPriority: 5,
        },
      ],
    },
  },
  topicBreakdown: {
    'topic-logic-syllogisms': {
      topicId: 'topic-logic-syllogisms',
      topicName: 'Critical Deduction & Syllogisms',
      subjectId: 'subj-logical-reasoning',
      subjectName: 'Logical Reasoning',
      chapterName: 'Critical Thinking & Deduction',
      attempted: 3,
      correct: 3,
      accuracy: 100,
      classification: 'strong',
      averageTimeSeconds: 45,
      confidenceDistribution: { low: 0, medium: 0, high: 3, unspecified: 0 },
      severity: 'none',
      yieldPriority: 5,
    },
    'topic-chem-le-chatelier': {
      topicId: 'topic-chem-le-chatelier',
      topicName: "Le Chatelier's Principle & Equilibrium Shifts",
      subjectId: 'subj-chemistry',
      subjectName: 'Chemistry',
      chapterName: 'Chemical Equilibrium',
      attempted: 5,
      correct: 2,
      accuracy: 40,
      classification: 'weak',
      averageTimeSeconds: 85,
      confidenceDistribution: { low: 2, medium: 2, high: 1, unspecified: 0 },
      severity: 'critical',
      yieldPriority: 5,
    },
    'topic-phy-coulomb-law': {
      topicId: 'topic-phy-coulomb-law',
      topicName: "Coulomb's Law & Electric Fields",
      subjectId: 'subj-physics',
      subjectName: 'Physics',
      chapterName: 'Electrostatics',
      attempted: 6,
      correct: 4,
      accuracy: 67,
      classification: 'developing',
      averageTimeSeconds: 78,
      confidenceDistribution: { low: 1, medium: 3, high: 2, unspecified: 0 },
      severity: 'minor',
      yieldPriority: 4,
    },
    'topic-bio-cell-structure': {
      topicId: 'topic-bio-cell-structure',
      topicName: 'Cell Structure & Organelle Functions',
      subjectId: 'subj-biology',
      subjectName: 'Biology',
      chapterName: 'Cell Biology',
      attempted: 12,
      correct: 9,
      accuracy: 75,
      classification: 'strong',
      averageTimeSeconds: 52,
      confidenceDistribution: { low: 1, medium: 3, high: 8, unspecified: 0 },
      severity: 'none',
      yieldPriority: 5,
    },
    'topic-chem-atomic-structure': {
      topicId: 'topic-chem-atomic-structure',
      topicName: 'Atomic Structure & Quantum Numbers',
      subjectId: 'subj-chemistry',
      subjectName: 'Chemistry',
      chapterName: 'Fundamental Principles',
      attempted: 4,
      correct: 3,
      accuracy: 75,
      classification: 'strong',
      averageTimeSeconds: 60,
      confidenceDistribution: { low: 0, medium: 1, high: 3, unspecified: 0 },
      severity: 'none',
      yieldPriority: 4,
    },
    'topic-eng-subject-verb': {
      topicId: 'topic-eng-subject-verb',
      topicName: 'Subject-Verb Agreement & Syntax Rules',
      subjectId: 'subj-english',
      subjectName: 'English',
      chapterName: 'Grammar & Mechanics',
      attempted: 3,
      correct: 3,
      accuracy: 100,
      classification: 'strong',
      averageTimeSeconds: 40,
      confidenceDistribution: { low: 0, medium: 0, high: 3, unspecified: 0 },
      severity: 'none',
      yieldPriority: 3,
    },
  },
  difficultyBreakdown: {
    easy: { difficulty: 'easy', total: 12, attempted: 12, correct: 10, accuracy: 83 },
    medium: { difficulty: 'medium', total: 12, attempted: 12, correct: 8, accuracy: 67 },
    hard: { difficulty: 'hard', total: 6, attempted: 6, correct: 3, accuracy: 50 },
    exam_level: { difficulty: 'exam_level', total: 0, attempted: 0, correct: 0, accuracy: 0 },
  },
  timePerformance: {
    totalTimeSpentSeconds: 2650,
    averageTimePerQuestionSeconds: 88,
    fastestQuestionSeconds: 35,
    slowestQuestionSeconds: 110,
    recommendedPacingSeconds: 75,
    pacingStanding: 'optimal',
  },
  confidenceBreakdown: {
    highConfidenceCount: 14,
    highConfidenceAccuracy: 86,
    mediumConfidenceCount: 10,
    mediumConfidenceAccuracy: 60,
    lowConfidenceCount: 6,
    lowConfidenceAccuracy: 33,
    unspecifiedCount: 0,
    calibrationStatus: 'well_calibrated',
    insightText:
      'High accuracy on high confidence Biology and English questions. Chemical equilibrium represents the primary barrier to breaking into the top 90th percentile.',
  },
  weakTopics: [
    {
      topicId: 'topic-chem-le-chatelier',
      topicName: "Le Chatelier's Principle & Equilibrium Shifts",
      subjectId: 'subj-chemistry',
      subjectName: 'Chemistry',
      chapterName: 'Chemical Equilibrium',
      attempted: 5,
      correct: 2,
      accuracy: 40,
      classification: 'weak',
      averageTimeSeconds: 85,
      confidenceDistribution: { low: 2, medium: 2, high: 1, unspecified: 0 },
      severity: 'critical',
      yieldPriority: 5,
    },
  ],
  strongTopics: [
    {
      topicId: 'topic-eng-subject-verb',
      topicName: 'Subject-Verb Agreement & Syntax Rules',
      subjectId: 'subj-english',
      subjectName: 'English',
      chapterName: 'Grammar & Mechanics',
      attempted: 3,
      correct: 3,
      accuracy: 100,
      classification: 'strong',
      averageTimeSeconds: 40,
      confidenceDistribution: { low: 0, medium: 0, high: 3, unspecified: 0 },
      severity: 'none',
      yieldPriority: 3,
    },
    {
      topicId: 'topic-bio-cell-structure',
      topicName: 'Cell Structure & Organelle Functions',
      subjectId: 'subj-biology',
      subjectName: 'Biology',
      chapterName: 'Cell Biology',
      attempted: 12,
      correct: 9,
      accuracy: 75,
      classification: 'strong',
      averageTimeSeconds: 52,
      confidenceDistribution: { low: 1, medium: 3, high: 8, unspecified: 0 },
      severity: 'none',
      yieldPriority: 5,
    },
  ],
  developingTopics: [
    {
      topicId: 'topic-phy-coulomb-law',
      topicName: "Coulomb's Law & Electric Fields",
      subjectId: 'subj-physics',
      subjectName: 'Physics',
      chapterName: 'Electrostatics',
      attempted: 6,
      correct: 4,
      accuracy: 67,
      classification: 'developing',
      averageTimeSeconds: 78,
      confidenceDistribution: { low: 1, medium: 3, high: 2, unspecified: 0 },
      severity: 'minor',
      yieldPriority: 4,
    },
  ],
  unknownTopics: [],
  recommendedNextStep: {
    topicId: 'topic-chem-le-chatelier',
    topicName: "Le Chatelier's Principle & Equilibrium Shifts",
    subjectName: 'Chemistry',
    chapterName: 'Chemical Equilibrium',
    learningUnitUrl: '/student/learn/topic-chem-le-chatelier',
    reason:
      'Ranked #1 Critical Gap: 40% accuracy on diagnostic test. Chemical equilibrium is tested in 4-6 PMDC MDCAT chemistry questions each year.',
    priority: 1,
    currentAccuracy: 40,
    estimatedMinutesToMastery: 40,
  },
  answers: [],
  subjectScores: {
    'subj-biology': { score: 9, maxScore: 12, accuracyPercentage: 75 },
    'subj-chemistry': { score: 5, maxScore: 9, accuracyPercentage: 56 },
    'subj-physics': { score: 4, maxScore: 6, accuracyPercentage: 67 },
    'subj-english': { score: 3, maxScore: 3, accuracyPercentage: 100 },
  },
  detectedWeaknesses: [
    {
      topicId: 'topic-chem-le-chatelier',
      topicName: "Le Chatelier's Principle & Equilibrium Shifts",
      subjectName: 'Chemistry',
      severity: 'critical',
      accuracy: 40,
    },
  ],
  aiDiagnosticSummary:
    'Strong biological foundational knowledge and perfect grammar syntax. Targeted revision on equilibrium shifts and endothermic/exothermic Le Chatelier stresses will propel your score toward UHS top tier merit.',
};


/**
 * Pre-populated Personalized Study Plan
 */
export const DEMO_STUDY_PLAN: StudyPlan & { coachingMessage?: string } = {
  id: 'plan-demo-ecat-01',
  studentId: DEMO_STUDENT_ID,
  examId: 'exam-ecat',
  title: 'ECAT High-Yield Diagnostic Recovery Sprint',
  goalExamDate: '2026-07-15',
  totalEstimatedHours: 28,
  status: 'active',
  coachingMessage:
    '🎯 Focus on circular motion sign conventions and Le Chatelier’s equilibrium shifts today. Your recent physics accuracy is trending up (+14%)—solidify the formulas before the mock exam.',
  createdAt: '2026-09-06T10:00:00.000Z',
  updatedAt: new Date().toISOString(),
};

export const DEMO_STUDY_PLAN_ITEMS: StudyPlanItem[] = [
  {
    id: 'item-demo-01',
    studyPlanId: 'plan-demo-ecat-01',
    studentId: DEMO_STUDENT_ID,
    topicId: 'topic-phy-centripetal-force',
    learningUnitId: 'unit-centripetal-force',
    priorityOrder: 1,
    status: 'in_progress',
    priorityReason:
      'Ranked #1 Critical Gap: 33% accuracy on diagnostic test. High-yield past paper topic (5-7% of Physics marks).',
    estimatedMinutes: 45,
  },
  {
    id: 'item-demo-02',
    studyPlanId: 'plan-demo-ecat-01',
    studentId: DEMO_STUDENT_ID,
    topicId: 'topic-chem-le-chatelier',
    learningUnitId: 'unit-le-chatelier',
    priorityOrder: 2,
    status: 'pending',
    priorityReason:
      'Ranked #2 Moderate Gap: 45% accuracy. Recurring question type in ECAT Paper Part II.',
    estimatedMinutes: 35,
  },
  {
    id: 'item-demo-03',
    studyPlanId: 'plan-demo-ecat-01',
    studentId: DEMO_STUDENT_ID,
    topicId: 'topic-math-chain-rule',
    priorityOrder: 3,
    status: 'pending',
    priorityReason:
      'Core calculus prerequisite needed for optimization and motion rate problems.',
    estimatedMinutes: 50,
  },
];

/**
 * Pre-populated Personalized Study Plan for MDCAT
 */
export const DEMO_MDCAT_STUDY_PLAN: StudyPlan & { coachingMessage?: string } = {
  id: 'plan-demo-mdcat-01',
  studentId: DEMO_STUDENT_ID,
  examId: 'exam-mdcat',
  title: 'MDCAT Medical Prep & Biology High-Yield Sprint',
  goalExamDate: '2026-08-25',
  totalEstimatedHours: 24,
  status: 'active',
  coachingMessage:
    '🎯 Focus on Cell Structure and membrane transport today. Biology carries 34% of MDCAT marks—solidify organelle mechanisms and fluid mosaic model principles before your next drill.',
  createdAt: '2026-09-06T10:00:00.000Z',
  updatedAt: new Date().toISOString(),
};

export const DEMO_MDCAT_STUDY_PLAN_ITEMS: StudyPlanItem[] = [
  {
    id: 'item-mdcat-01',
    studyPlanId: 'plan-demo-mdcat-01',
    studentId: DEMO_STUDENT_ID,
    topicId: 'topic-bio-cell-structure',
    learningUnitId: 'unit-cell-structure',
    priorityOrder: 1,
    status: 'in_progress',
    priorityReason:
      'Core High-Yield Topic: 34% of MDCAT weight. Membrane transport & enzyme organelle mechanics.',
    estimatedMinutes: 40,
  },
  {
    id: 'item-mdcat-02',
    studyPlanId: 'plan-demo-mdcat-01',
    studentId: DEMO_STUDENT_ID,
    topicId: 'topic-chem-le-chatelier',
    learningUnitId: 'unit-le-chatelier',
    priorityOrder: 2,
    status: 'pending',
    priorityReason:
      'Ranked #2 Moderate Gap: 40% accuracy in diagnostic. Essential equilibrium shifts and buffer systems.',
    estimatedMinutes: 35,
  },
  {
    id: 'item-mdcat-03',
    studyPlanId: 'plan-demo-mdcat-01',
    studentId: DEMO_STUDENT_ID,
    topicId: 'topic-phy-centripetal-force',
    learningUnitId: 'unit-centripetal-force',
    priorityOrder: 3,
    status: 'pending',
    priorityReason:
      'Circular motion mechanics & acceleration vectors in biomedical systems.',
    estimatedMinutes: 45,
  },
];

/**
 * Pre-populated Interactive Tutor Session
 */
export const DEMO_TUTOR_SESSION: TutorSession = {
  id: 'session-demo-01',
  studentId: DEMO_STUDENT_ID,
  topicId: 'topic-phy-centripetal-force',
  questionId: 'q-phy-01',
  title: 'Centripetal Force & Flat Curve Skidding Discussion',
  status: 'active',
  messages: [
    {
      id: 'msg-01',
      role: 'tutor',
      content:
        "Hello Shamil! I noticed you were reviewing unbanked road curves. Remember, on a flat curve, what provides the centripetal force preventing the car from skidding outwards?",
      timestamp: '2026-09-09T14:02:00.000Z',
    },
    {
      id: 'msg-02',
      role: 'student',
      content:
        'Is it the normal force or friction force?',
      timestamp: '2026-09-09T14:03:30.000Z',
    },
    {
      id: 'msg-03',
      role: 'tutor',
      content:
        'Spot on! On a completely flat road, the normal force points straight up (balancing gravity mg), so it has zero horizontal component. That means 100% of the inward radial force must come from static friction: f_s = μ · N = μ · m · g. Setting this equal to m·v²/r gives v_max = √(μ · g · r). Notice how mass cancels out?',
      timestamp: '2026-09-09T14:04:15.000Z',
    },
  ],
  summary: 'Clarified normal force vs static friction components on flat circular curves.',
  createdAt: '2026-09-09T14:00:00.000Z',
  updatedAt: new Date().toISOString(),
};
